name: Studio CI
on:
  push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: echo
        run: echo 'start build'
      - name: build
        run: npm run docs:build
      - name: tar
        run: tar -czvf dist.tar dist && ls -l # 目标文件进行打包
      - name: Upload to Server
        uses: easingthemes/ssh-deploy@main
        env:
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USER }}
            SSH_PRIVATE_KEY: ${{ secrets.KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "dist.tar"
            TARGET: "/home/azi/web/dist/studio.tar"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/azi/web/scripts && bash ./studio-deploy.sh
