name: Studio CI
on:
  push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: echo
        run: echo 'start build'
      - name: build
        run: npm run docs:build
      - name: tar
        run: tar -czvf dist.tar dist # 目标文件进行打包
      - name: Create Release
        # You may pin to the exact commit or the version.
        # uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
        uses: ncipollo/release-action@v1.10.0
